// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/book": {
    params: {};
  };
  "/book/confirm": {
    params: {};
  };
  "/book/time": {
    params: {};
  };
  "/manage-bookings": {
    params: {};
  };
  "/my-bookings": {
    params: {};
  };
  "/salon-dashboard": {
    params: {};
  };
  "/salon-setup": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/signin" | "/book" | "/book/confirm" | "/book/time" | "/manage-bookings" | "/my-bookings" | "/salon-dashboard" | "/salon-setup" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./book/page.jsx": {
    id: "book/page";
    page: "/book";
  };
  "./book/confirm/page.jsx": {
    id: "book/confirm/page";
    page: "/book/confirm";
  };
  "./book/time/page.jsx": {
    id: "book/time/page";
    page: "/book/time";
  };
  "./manage-bookings/page.jsx": {
    id: "manage-bookings/page";
    page: "/manage-bookings";
  };
  "./my-bookings/page.jsx": {
    id: "my-bookings/page";
    page: "/my-bookings";
  };
  "./salon-dashboard/page.jsx": {
    id: "salon-dashboard/page";
    page: "/salon-dashboard";
  };
  "./salon-setup/page.jsx": {
    id: "salon-setup/page";
    page: "/salon-setup";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "book/page": typeof import("./src/app/./book/page.jsx");
  "book/confirm/page": typeof import("./src/app/./book/confirm/page.jsx");
  "book/time/page": typeof import("./src/app/./book/time/page.jsx");
  "manage-bookings/page": typeof import("./src/app/./manage-bookings/page.jsx");
  "my-bookings/page": typeof import("./src/app/./my-bookings/page.jsx");
  "salon-dashboard/page": typeof import("./src/app/./salon-dashboard/page.jsx");
  "salon-setup/page": typeof import("./src/app/./salon-setup/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};